# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa2f06005921697b48c4fdd9b9373f49a66451aedd7b95ec79beac0c2d9a8460cbdb86ecff097d94362e021eebd4e36f0597279c8c6435c7d4f4dc3c805625f

test:
  secret_key_base: bd051f5796703954a967ab604789ac216927d5633ef0a80831fbcee10d123b5f577f3ed4c295290806e8cc6ac186a64147e79fb331ad3e974f7379cd154aec93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
